
package temp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviceInter", targetNamespace = "http://temp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceInter {


    /**
     * 
     * @param url
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "check", targetNamespace = "http://temp/", className = "temp.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://temp/", className = "temp.CheckResponse")
    @Action(input = "http://temp/serviceInter/checkRequest", output = "http://temp/serviceInter/checkResponse")
    public boolean check(
        @WebParam(name = "url", targetNamespace = "")
        String url);

    /**
     * 
     * @param payload
     * @param theme
     * @param url
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmailDemo", targetNamespace = "http://temp/", className = "temp.SendEmailDemo")
    @ResponseWrapper(localName = "sendEmailDemoResponse", targetNamespace = "http://temp/", className = "temp.SendEmailDemoResponse")
    @Action(input = "http://temp/serviceInter/sendEmailDemoRequest", output = "http://temp/serviceInter/sendEmailDemoResponse")
    public boolean sendEmailDemo(
        @WebParam(name = "url", targetNamespace = "")
        List<String> url,
        @WebParam(name = "payload", targetNamespace = "")
        String payload,
        @WebParam(name = "theme", targetNamespace = "")
        String theme);

}
